# --- Services ---
services:
  # Application principale
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tanstack-forum-app
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env.prod
      # Fallback to .env for dev/defaults if needed, but .env.prod should take precedence
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - ORIGIN=https://${DOMAIN_NAME}
    ports:
      - "3000:3000"
    networks:
      - app_network

  # Base de données PostgreSQL
  postgres:
    image: postgres:17-alpine
    container_name: tanstack-forum-db-prod
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data
    networks:
      - app_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres_prod_data:


networks:
  app_network:
    driver: bridge
