/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestEmailRouteImport } from './routes/test-email'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as HelpRouteImport } from './routes/help'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ThreadsIndexRouteImport } from './routes/threads/index'
import { Route as SearchIndexRouteImport } from './routes/search/index'
import { Route as ThreadsConfirmationRouteImport } from './routes/threads/confirmation'
import { Route as ThreadsThreadSlugRouteImport } from './routes/threads/$threadSlug'
import { Route as AuthAnonymousSigninRouteImport } from './routes/auth/anonymous-signin'
import { Route as ThreadsNewIndexRouteImport } from './routes/threads/new/index'
import { Route as AuthResetPasswordIndexRouteImport } from './routes/auth/reset-password/index'
import { Route as AuthLoginIndexRouteImport } from './routes/auth/login/index'
import { Route as AdminModerationIndexRouteImport } from './routes/admin/moderation/index'
import { Route as AccountSettingsIndexRouteImport } from './routes/account/settings/index'
import { Route as AccountProfileIndexRouteImport } from './routes/account/profile/index'
import { Route as ThreadsNewCategoryRouteImport } from './routes/threads/new/$category'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const TestEmailRoute = TestEmailRouteImport.update({
  id: '/test-email',
  path: '/test-email',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ThreadsIndexRoute = ThreadsIndexRouteImport.update({
  id: '/threads/',
  path: '/threads/',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchIndexRoute = SearchIndexRouteImport.update({
  id: '/search/',
  path: '/search/',
  getParentRoute: () => rootRouteImport,
} as any)
const ThreadsConfirmationRoute = ThreadsConfirmationRouteImport.update({
  id: '/threads/confirmation',
  path: '/threads/confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const ThreadsThreadSlugRoute = ThreadsThreadSlugRouteImport.update({
  id: '/threads/$threadSlug',
  path: '/threads/$threadSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAnonymousSigninRoute = AuthAnonymousSigninRouteImport.update({
  id: '/auth/anonymous-signin',
  path: '/auth/anonymous-signin',
  getParentRoute: () => rootRouteImport,
} as any)
const ThreadsNewIndexRoute = ThreadsNewIndexRouteImport.update({
  id: '/threads/new/',
  path: '/threads/new/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordIndexRoute = AuthResetPasswordIndexRouteImport.update({
  id: '/auth/reset-password/',
  path: '/auth/reset-password/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/auth/login/',
  path: '/auth/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminModerationIndexRoute = AdminModerationIndexRouteImport.update({
  id: '/admin/moderation/',
  path: '/admin/moderation/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountSettingsIndexRoute = AccountSettingsIndexRouteImport.update({
  id: '/account/settings/',
  path: '/account/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountProfileIndexRoute = AccountProfileIndexRouteImport.update({
  id: '/account/profile/',
  path: '/account/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const ThreadsNewCategoryRoute = ThreadsNewCategoryRouteImport.update({
  id: '/threads/new/$category',
  path: '/threads/new/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/help': typeof HelpRoute
  '/privacy': typeof PrivacyRoute
  '/rules': typeof RulesRoute
  '/test-email': typeof TestEmailRoute
  '/auth/anonymous-signin': typeof AuthAnonymousSigninRoute
  '/threads/$threadSlug': typeof ThreadsThreadSlugRoute
  '/threads/confirmation': typeof ThreadsConfirmationRoute
  '/search/': typeof SearchIndexRoute
  '/threads/': typeof ThreadsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/threads/new/$category': typeof ThreadsNewCategoryRoute
  '/account/profile/': typeof AccountProfileIndexRoute
  '/account/settings/': typeof AccountSettingsIndexRoute
  '/admin/moderation/': typeof AdminModerationIndexRoute
  '/auth/login/': typeof AuthLoginIndexRoute
  '/auth/reset-password/': typeof AuthResetPasswordIndexRoute
  '/threads/new/': typeof ThreadsNewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/help': typeof HelpRoute
  '/privacy': typeof PrivacyRoute
  '/rules': typeof RulesRoute
  '/test-email': typeof TestEmailRoute
  '/auth/anonymous-signin': typeof AuthAnonymousSigninRoute
  '/threads/$threadSlug': typeof ThreadsThreadSlugRoute
  '/threads/confirmation': typeof ThreadsConfirmationRoute
  '/search': typeof SearchIndexRoute
  '/threads': typeof ThreadsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/threads/new/$category': typeof ThreadsNewCategoryRoute
  '/account/profile': typeof AccountProfileIndexRoute
  '/account/settings': typeof AccountSettingsIndexRoute
  '/admin/moderation': typeof AdminModerationIndexRoute
  '/auth/login': typeof AuthLoginIndexRoute
  '/auth/reset-password': typeof AuthResetPasswordIndexRoute
  '/threads/new': typeof ThreadsNewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/help': typeof HelpRoute
  '/privacy': typeof PrivacyRoute
  '/rules': typeof RulesRoute
  '/test-email': typeof TestEmailRoute
  '/auth/anonymous-signin': typeof AuthAnonymousSigninRoute
  '/threads/$threadSlug': typeof ThreadsThreadSlugRoute
  '/threads/confirmation': typeof ThreadsConfirmationRoute
  '/search/': typeof SearchIndexRoute
  '/threads/': typeof ThreadsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/threads/new/$category': typeof ThreadsNewCategoryRoute
  '/account/profile/': typeof AccountProfileIndexRoute
  '/account/settings/': typeof AccountSettingsIndexRoute
  '/admin/moderation/': typeof AdminModerationIndexRoute
  '/auth/login/': typeof AuthLoginIndexRoute
  '/auth/reset-password/': typeof AuthResetPasswordIndexRoute
  '/threads/new/': typeof ThreadsNewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/help'
    | '/privacy'
    | '/rules'
    | '/test-email'
    | '/auth/anonymous-signin'
    | '/threads/$threadSlug'
    | '/threads/confirmation'
    | '/search/'
    | '/threads/'
    | '/api/auth/$'
    | '/threads/new/$category'
    | '/account/profile/'
    | '/account/settings/'
    | '/admin/moderation/'
    | '/auth/login/'
    | '/auth/reset-password/'
    | '/threads/new/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/help'
    | '/privacy'
    | '/rules'
    | '/test-email'
    | '/auth/anonymous-signin'
    | '/threads/$threadSlug'
    | '/threads/confirmation'
    | '/search'
    | '/threads'
    | '/api/auth/$'
    | '/threads/new/$category'
    | '/account/profile'
    | '/account/settings'
    | '/admin/moderation'
    | '/auth/login'
    | '/auth/reset-password'
    | '/threads/new'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/help'
    | '/privacy'
    | '/rules'
    | '/test-email'
    | '/auth/anonymous-signin'
    | '/threads/$threadSlug'
    | '/threads/confirmation'
    | '/search/'
    | '/threads/'
    | '/api/auth/$'
    | '/threads/new/$category'
    | '/account/profile/'
    | '/account/settings/'
    | '/admin/moderation/'
    | '/auth/login/'
    | '/auth/reset-password/'
    | '/threads/new/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  HelpRoute: typeof HelpRoute
  PrivacyRoute: typeof PrivacyRoute
  RulesRoute: typeof RulesRoute
  TestEmailRoute: typeof TestEmailRoute
  AuthAnonymousSigninRoute: typeof AuthAnonymousSigninRoute
  ThreadsThreadSlugRoute: typeof ThreadsThreadSlugRoute
  ThreadsConfirmationRoute: typeof ThreadsConfirmationRoute
  SearchIndexRoute: typeof SearchIndexRoute
  ThreadsIndexRoute: typeof ThreadsIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ThreadsNewCategoryRoute: typeof ThreadsNewCategoryRoute
  AccountProfileIndexRoute: typeof AccountProfileIndexRoute
  AccountSettingsIndexRoute: typeof AccountSettingsIndexRoute
  AdminModerationIndexRoute: typeof AdminModerationIndexRoute
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
  AuthResetPasswordIndexRoute: typeof AuthResetPasswordIndexRoute
  ThreadsNewIndexRoute: typeof ThreadsNewIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test-email': {
      id: '/test-email'
      path: '/test-email'
      fullPath: '/test-email'
      preLoaderRoute: typeof TestEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/threads/': {
      id: '/threads/'
      path: '/threads'
      fullPath: '/threads/'
      preLoaderRoute: typeof ThreadsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search/': {
      id: '/search/'
      path: '/search'
      fullPath: '/search/'
      preLoaderRoute: typeof SearchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/threads/confirmation': {
      id: '/threads/confirmation'
      path: '/threads/confirmation'
      fullPath: '/threads/confirmation'
      preLoaderRoute: typeof ThreadsConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/threads/$threadSlug': {
      id: '/threads/$threadSlug'
      path: '/threads/$threadSlug'
      fullPath: '/threads/$threadSlug'
      preLoaderRoute: typeof ThreadsThreadSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/anonymous-signin': {
      id: '/auth/anonymous-signin'
      path: '/auth/anonymous-signin'
      fullPath: '/auth/anonymous-signin'
      preLoaderRoute: typeof AuthAnonymousSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/threads/new/': {
      id: '/threads/new/'
      path: '/threads/new'
      fullPath: '/threads/new/'
      preLoaderRoute: typeof ThreadsNewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password/': {
      id: '/auth/reset-password/'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password/'
      preLoaderRoute: typeof AuthResetPasswordIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login/': {
      id: '/auth/login/'
      path: '/auth/login'
      fullPath: '/auth/login/'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/moderation/': {
      id: '/admin/moderation/'
      path: '/admin/moderation'
      fullPath: '/admin/moderation/'
      preLoaderRoute: typeof AdminModerationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/settings/': {
      id: '/account/settings/'
      path: '/account/settings'
      fullPath: '/account/settings/'
      preLoaderRoute: typeof AccountSettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/profile/': {
      id: '/account/profile/'
      path: '/account/profile'
      fullPath: '/account/profile/'
      preLoaderRoute: typeof AccountProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/threads/new/$category': {
      id: '/threads/new/$category'
      path: '/threads/new/$category'
      fullPath: '/threads/new/$category'
      preLoaderRoute: typeof ThreadsNewCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  HelpRoute: HelpRoute,
  PrivacyRoute: PrivacyRoute,
  RulesRoute: RulesRoute,
  TestEmailRoute: TestEmailRoute,
  AuthAnonymousSigninRoute: AuthAnonymousSigninRoute,
  ThreadsThreadSlugRoute: ThreadsThreadSlugRoute,
  ThreadsConfirmationRoute: ThreadsConfirmationRoute,
  SearchIndexRoute: SearchIndexRoute,
  ThreadsIndexRoute: ThreadsIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ThreadsNewCategoryRoute: ThreadsNewCategoryRoute,
  AccountProfileIndexRoute: AccountProfileIndexRoute,
  AccountSettingsIndexRoute: AccountSettingsIndexRoute,
  AdminModerationIndexRoute: AdminModerationIndexRoute,
  AuthLoginIndexRoute: AuthLoginIndexRoute,
  AuthResetPasswordIndexRoute: AuthResetPasswordIndexRoute,
  ThreadsNewIndexRoute: ThreadsNewIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
